### ISSUE TITLE
Add Helm chart

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/crafty#15]
https://github.com/puppetlabs/puppetserver-helm-chart/ might be a good staring point.

**Comment by rwaffen** [comment]
@bastelfreak @tuxmea @marcusdots
how do you see this: do we want to create a own helm or do we use this from puppetlabs?

**Comment by tuxmea** [comment]
I don't see a benefit in developing and maintaining multiple helm charts.
Let's add a link to the one from PuppetLabs GitHub repo.
