### ISSUE TITLE
Renaming images or adding a shorter name?

### ISSUE THREAD

**Issue by rwaffen** [voxpupuli/crafty#61]
### Discussed in https://github.com/voxpupuli/crafty/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **rwaffen** April  4, 2024</sup>
initially I named the git repo container-puppetserver / container-puppetdb. this was to make sure it is not confused with the real git projects from puppet and make sure you can see that this only is for container builds. 

but so also the package/container image itself is called that way. but recently i found out, that this has not to be like that.

the image name now
`voxpupuli/container-puppetserver:latest`

shot name:
`voxpupuli/puppetserver:latest`

so we could build a package only called puppetserver and add it to the registry. the question is now: do we want to do this? do we want to rename it or add a second package/image with the short name?

or do we just keep the names now?

any suggestions?</div>

as discussed we can use the shorter names

- [ ] create shortname dockerhub repos
- [ ] add short name to github
- [ ] push also to shortname docker repos

**Comment by bastelfreak** [comment]
I think a second name is fine. Renaming can always result in strange errors and I don't think the old name is too bad.

**Comment by tuxmea** [comment]
I would recommend to keep the long name and add the short name.
Next we can make an announcement, that we switch names and can afterwards remove the long names.
This will give users the option to migrate over time.

my 5pc.

**Comment by rwaffen** [comment]
okay, will keep the old names and only add the new. issues was a bit unclear from wording, just created it from discussion.
